## Import Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

file_path = "data.csv"

# 读取CSV文件
df = pd.read_csv(file_path)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1879 entries, 0 to 1878
Data columns (total 46 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   PatientID                      1879 non-null   int64  
 1   Age                            1879 non-null   int64  
 2   Gender                         1879 non-null   int64  
 3   Ethnicity                      1879 non-null   int64  
 4   SocioeconomicStatus            1879 non-null   int64  
 5   EducationLevel                 1879 non-null   int64  
 6   BMI                            1879 non-null   float64
 7   Smoking                        1879 non-null   int64  
 8   AlcoholConsumption             1879 non-null   float64
 9   PhysicalActivity               1879 non-null   float64
 10  DietQuality                    1879 non-null   float64
 11  SleepQuality                   1879 non-null   float64
 12  FamilyHistoryDiabetes          1879 non-null   i

In [3]:
pd.set_option('display.width', 500)

df.head(10)

PatientID  Age  Gender  Ethnicity  SocioeconomicStatus  EducationLevel        BMI  Smoking  AlcoholConsumption  PhysicalActivity  ...  TinglingHandsFeet  QualityOfLifeScore  HeavyMetalsExposure  OccupationalExposureChemicals  WaterQuality  MedicalCheckupsFrequency  MedicationAdherence  HealthLiteracy  Diagnosis  DoctorInCharge
0       6000   44       0          1                    2               1  32.985284        1            4.499365          2.443385  ...                  1           73.765109                    0                              0             0                  1.782724             4.486980        7.211349          1    Confidential
1       6001   51       1          0                    1               2  39.916764        0            1.578919          8.301264  ...                  0           91.445753                    0                              0             1                  3.381070             5.961705        5.024612          1    Confidential
2       6002   89       1          0                    1               3  19.782251        0            1.177301          6.103395  ...                  0           54.485744                    0                              0             0                  2.701019             8.950821        7.034944          0    Confidential
3       6003   21       1          1                    1               2  32.376881        1            1.714621          8.645465  ...                  0           77.866758                    0                              0             1                  1.409056             3.124769        4.717774          0    Confidential
4       6004   27       1          0                    1               3  16.808600        0           15.462549          4.629383  ...                  0           37.731808                    0                              0             0                  1.218452             6.977741        7.887940          0    Confidential
5       6005   65       0          0                    0               0  15.820815        1           17.781024          9.252522  ...                  0           86.378969                    0                              0             0                  1.535161             9.682226        2.744281          0    Confidential
6       6006   61       1          2                    1               3  20.075147        0            1.086479          8.745650  ...                  0           86.036931                    0                              0             0                  0.578208             1.175504        1.229453          0    Confidential
7       6007   74       1          3                    0               3  29.438938        0            6.187378          9.114535  ...                  0           47.315820                    0                              0             0                  1.659424             2.258377        9.035877          0    Confidential
8       6008   54       0          0                    1               2  15.027557        0           19.505734          0.590771  ...                  0           88.638130                    0                              0             0                  3.675916             2.006186        3.452805          1    Confidential
9       6009   82       1          0                    1               1  34.300044        1           15.943844          6.056621  ...                  0           96.636541                    0                              0             0                  2.567315             4.031643        2.633287          0    Confidential

[10 rows x 46 columns]

In [4]:
df.describe()

PatientID          Age       Gender    Ethnicity  SocioeconomicStatus  EducationLevel          BMI      Smoking  AlcoholConsumption  PhysicalActivity  ...  SlowHealingSores  TinglingHandsFeet  QualityOfLifeScore  HeavyMetalsExposure  OccupationalExposureChemicals  WaterQuality  MedicalCheckupsFrequency  MedicationAdherence  HealthLiteracy    Diagnosis
count  1879.000000  1879.000000  1879.000000  1879.000000          1879.000000     1879.000000  1879.000000  1879.000000         1879.000000       1879.000000  ...       1879.000000        1879.000000         1879.000000          1879.000000                    1879.000000   1879.000000               1879.000000          1879.000000     1879.000000  1879.000000
mean   6939.000000    55.043108     0.487493     0.755721             0.992017        1.699308    27.687601     0.281533           10.096587          5.200790  ...          0.102714           0.111229           48.508643             0.052155                       0.103246      0.200639                  1.997101             4.957539        5.011736     0.400213
std     542.564896    20.515839     0.499977     1.047558             0.764940        0.885665     7.190975     0.449866            5.914216          2.857012  ...          0.303666           0.314500           28.758488             0.222400                       0.304361      0.400585                  1.122632             2.910934        2.920908     0.490072
min    6000.000000    20.000000     0.000000     0.000000             0.000000        0.000000    15.025898     0.000000            0.000928          0.004089  ...          0.000000           0.000000            0.002390             0.000000                       0.000000      0.000000                  0.004013             0.005384        0.000362     0.000000
25%    6469.500000    38.000000     0.000000     0.000000             0.000000        1.000000    21.469981     0.000000            4.789725          2.751022  ...          0.000000           0.000000           23.974098             0.000000                       0.000000      0.000000                  1.057801             2.420024        2.410113     0.000000
50%    6939.000000    55.000000     0.000000     0.000000             1.000000        2.000000    27.722988     0.000000           10.173865          5.249002  ...          0.000000           0.000000           47.519693             0.000000                       0.000000      0.000000                  1.987170             4.843886        5.035208     0.000000
75%    7408.500000    73.000000     1.000000     1.000000             2.000000        2.000000    33.856460     1.000000           15.285359          7.671402  ...          0.000000           0.000000           72.883179             0.000000                       0.000000      0.000000                  2.946019             7.513933        7.586865     1.000000
max    7878.000000    90.000000     1.000000     3.000000             2.000000        3.000000    39.998811     1.000000           19.996231          9.993893  ...          1.000000           1.000000           99.788530             1.000000                       1.000000      1.000000                  3.999715             9.997165        9.993029     1.000000

[8 rows x 45 columns]

In [5]:
df.duplicated().sum()

0

In [2]:
# 单变量特征选择
from sklearn.feature_selection import SelectKBest, f_classif, chi2, mutual_info_classif

# 加载数据
import pandas as pd
X = df.drop(['PatientID', 'Diagnosis', 'DoctorInCharge'], axis=1)
y = df['Diagnosis']

# 连续特征的F检验
selector_f = SelectKBest(f_classif, k=15)
X_f = selector_f.fit_transform(X, y)
selected_features_f = X.columns[selector_f.get_support()]

# 互信息法 (适用于非线性关系)
selector_mi = SelectKBest(mutual_info_classif, k=15)
X_mi = selector_mi.fit_transform(X, y)
selected_features_mi = X.columns[selector_mi.get_support()]

print("F检验选择的特征:", selected_features_f)
print("互信息选择的特征:", selected_features_mi)


F检验选择的特征: Index(['Smoking', 'DietQuality', 'FamilyHistoryDiabetes',
       'PolycysticOvarySyndrome', 'Hypertension', 'SystolicBP', 'DiastolicBP',
       'FastingBloodSugar', 'HbA1c', 'FrequentUrination', 'ExcessiveThirst',
       'UnexplainedWeightLoss', 'BlurredVision', 'QualityOfLifeScore',
       'WaterQuality'],
      dtype='object')
互信息选择的特征: Index(['Age', 'SocioeconomicStatus', 'EducationLevel', 'PhysicalActivity',
       'SleepQuality', 'GestationalDiabetes', 'SystolicBP',
       'FastingBloodSugar', 'HbA1c', 'SerumCreatinine', 'CholesterolHDL',
       'FrequentUrination', 'SlowHealingSores', 'QualityOfLifeScore',
       'MedicationAdherence'],
      dtype='object')


In [3]:
# 递归特征消除
from sklearn.feature_selection import RFECV
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
selector = RFECV(model, step=1, cv=5, scoring='roc_auc')
selector.fit(X, y)

selected_features_rfe = X.columns[selector.support_]
print("RFE选择的特征:", selected_features_rfe)

print(len(selected_features_rfe))


RFE选择的特征: Index(['Age', 'Gender', 'Ethnicity', 'SocioeconomicStatus', 'EducationLevel',
       'BMI', 'Smoking', 'AlcoholConsumption', 'PhysicalActivity',
       'DietQuality', 'SleepQuality', 'FamilyHistoryDiabetes',
       'PreviousPreDiabetes', 'Hypertension', 'SystolicBP', 'DiastolicBP',
       'FastingBloodSugar', 'HbA1c', 'SerumCreatinine', 'BUNLevels',
       'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
       'CholesterolTriglycerides', 'AntihypertensiveMedications', 'Statins',
       'AntidiabeticMedications', 'FrequentUrination', 'ExcessiveThirst',
       'UnexplainedWeightLoss', 'FatigueLevels', 'BlurredVision',
       'SlowHealingSores', 'QualityOfLifeScore', 'WaterQuality',
       'MedicalCheckupsFrequency', 'MedicationAdherence', 'HealthLiteracy'],
      dtype='object')
38


In [7]:
# 基于树模型的特征重要性
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import numpy as np

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

# 获取特征重要性
importances = model.feature_importances_
indices = np.argsort(importances)[::-1]

# 选择前15个重要特征
selected_features_rf = X.columns[indices[:15]]
print("随机森林选择的特征:", selected_features_rf)
print(len(selected_features_rf))

# L1正则化 (Lasso)
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel

model = LogisticRegression(C=0.1, penalty='l1', solver='liblinear', random_state=42)
selector = SelectFromModel(model)
selector.fit(X, y)

selected_features_l1 = X.columns[selector.get_support()]
print("L1正则化选择的特征:", selected_features_l1)
print(len(selected_features_l1))

随机森林选择的特征: Index(['HbA1c', 'FastingBloodSugar', 'HealthLiteracy', 'BUNLevels',
       'CholesterolHDL', 'CholesterolLDL', 'CholesterolTriglycerides',
       'SystolicBP', 'DietQuality', 'CholesterolTotal',
       'MedicalCheckupsFrequency', 'PhysicalActivity', 'DiastolicBP',
       'SerumCreatinine', 'FatigueLevels'],
      dtype='object')
15
L1正则化选择的特征: Index(['Age', 'Ethnicity', 'SocioeconomicStatus', 'EducationLevel', 'BMI',
       'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality',
       'SleepQuality', 'Hypertension', 'SystolicBP', 'DiastolicBP',
       'FastingBloodSugar', 'HbA1c', 'SerumCreatinine', 'BUNLevels',
       'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL', 'Statins',
       'FrequentUrination', 'ExcessiveThirst', 'UnexplainedWeightLoss',
       'FatigueLevels', 'BlurredVision', 'QualityOfLifeScore',
       'MedicalCheckupsFrequency', 'MedicationAdherence', 'HealthLiteracy'],
      dtype='object')
30


In [8]:
# F检验选择的特征
X_F = df[['Smoking', 'DietQuality', 'FamilyHistoryDiabetes',
       'PolycysticOvarySyndrome', 'Hypertension', 'SystolicBP', 'DiastolicBP',
       'FastingBloodSugar', 'HbA1c', 'FrequentUrination', 'ExcessiveThirst',
       'UnexplainedWeightLoss', 'BlurredVision', 'QualityOfLifeScore',
       'WaterQuality']]
y_F = df['Diagnosis']

In [21]:
# mi
X_mi = df[['Age', 'SocioeconomicStatus', 'EducationLevel', 'PhysicalActivity',
       'SleepQuality', 'GestationalDiabetes', 'SystolicBP',
       'FastingBloodSugar', 'HbA1c', 'SerumCreatinine', 'CholesterolHDL',
       'FrequentUrination', 'SlowHealingSores', 'QualityOfLifeScore',
       'MedicationAdherence']]
y_mi = df['Diagnosis']

In [10]:
# RFE选择的特征
X_RFE = df[['Age', 'Gender', 'Ethnicity', 'SocioeconomicStatus', 'EducationLevel',
       'BMI', 'Smoking', 'AlcoholConsumption', 'PhysicalActivity',
       'DietQuality', 'SleepQuality', 'FamilyHistoryDiabetes',
       'PreviousPreDiabetes', 'Hypertension', 'SystolicBP', 'DiastolicBP',
       'FastingBloodSugar', 'HbA1c', 'SerumCreatinine', 'BUNLevels',
       'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
       'CholesterolTriglycerides', 'AntihypertensiveMedications', 'Statins',
       'AntidiabeticMedications', 'FrequentUrination', 'ExcessiveThirst',
       'UnexplainedWeightLoss', 'FatigueLevels', 'BlurredVision',
       'SlowHealingSores', 'QualityOfLifeScore', 'WaterQuality',
       'MedicalCheckupsFrequency', 'MedicationAdherence', 'HealthLiteracy']]
y_RFE = df['Diagnosis']

In [11]:
# 随机森林选择的特征
X_RF = df[['HbA1c', 'FastingBloodSugar', 'HealthLiteracy', 'BUNLevels',
       'CholesterolHDL', 'CholesterolLDL', 'CholesterolTriglycerides',
       'SystolicBP', 'DietQuality', 'CholesterolTotal',
       'MedicalCheckupsFrequency', 'PhysicalActivity', 'DiastolicBP',
       'SerumCreatinine', 'FatigueLevels']]
y_RF = df['Diagnosis']

In [12]:
# L1正则化
X_l1 = df[['Age', 'Ethnicity', 'SocioeconomicStatus', 'EducationLevel', 'BMI', 'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality', 'Hypertension', 'SystolicBP', 'DiastolicBP', 'FastingBloodSugar', 'HbA1c', 'SerumCreatinine', 'BUNLevels', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL', 'Statins', 'FrequentUrination', 'ExcessiveThirst', 'UnexplainedWeightLoss', 'FatigueLevels', 'BlurredVision', 'QualityOfLifeScore', 'MedicalCheckupsFrequency',
       'MedicationAdherence', 'HealthLiteracy']]
y_l1 = df['Diagnosis']

## Normalization

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def normalization_function(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    
    return X_train, X_test, y_train, y_test

In [13]:
df.describe()

PatientID          Age       Gender    Ethnicity  SocioeconomicStatus  EducationLevel          BMI      Smoking  AlcoholConsumption  PhysicalActivity  ...  SlowHealingSores  TinglingHandsFeet  QualityOfLifeScore  HeavyMetalsExposure  OccupationalExposureChemicals  WaterQuality  MedicalCheckupsFrequency  MedicationAdherence  HealthLiteracy    Diagnosis
count  1879.000000  1879.000000  1879.000000  1879.000000          1879.000000     1879.000000  1879.000000  1879.000000         1879.000000       1879.000000  ...       1879.000000        1879.000000         1879.000000          1879.000000                    1879.000000   1879.000000               1879.000000          1879.000000     1879.000000  1879.000000
mean   6939.000000    55.043108     0.487493     0.755721             0.992017        1.699308    27.687601     0.281533           10.096587          5.200790  ...          0.102714           0.111229           48.508643             0.052155                       0.103246      0.200639                  1.997101             4.957539        5.011736     0.400213
std     542.564896    20.515839     0.499977     1.047558             0.764940        0.885665     7.190975     0.449866            5.914216          2.857012  ...          0.303666           0.314500           28.758488             0.222400                       0.304361      0.400585                  1.122632             2.910934        2.920908     0.490072
min    6000.000000    20.000000     0.000000     0.000000             0.000000        0.000000    15.025898     0.000000            0.000928          0.004089  ...          0.000000           0.000000            0.002390             0.000000                       0.000000      0.000000                  0.004013             0.005384        0.000362     0.000000
25%    6469.500000    38.000000     0.000000     0.000000             0.000000        1.000000    21.469981     0.000000            4.789725          2.751022  ...          0.000000           0.000000           23.974098             0.000000                       0.000000      0.000000                  1.057801             2.420024        2.410113     0.000000
50%    6939.000000    55.000000     0.000000     0.000000             1.000000        2.000000    27.722988     0.000000           10.173865          5.249002  ...          0.000000           0.000000           47.519693             0.000000                       0.000000      0.000000                  1.987170             4.843886        5.035208     0.000000
75%    7408.500000    73.000000     1.000000     1.000000             2.000000        2.000000    33.856460     1.000000           15.285359          7.671402  ...          0.000000           0.000000           72.883179             0.000000                       0.000000      0.000000                  2.946019             7.513933        7.586865     1.000000
max    7878.000000    90.000000     1.000000     3.000000             2.000000        3.000000    39.998811     1.000000           19.996231          9.993893  ...          1.000000           1.000000           99.788530             1.000000                       1.000000      1.000000                  3.999715             9.997165        9.993029     1.000000

[8 rows x 45 columns]

## Logistic regression (baseline)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

def get_model(X_train,X_test,y_train,y_test):

    model = LogisticRegression(random_state=42)
    model.fit(X_train, y_train)

    # 交叉验证
    from sklearn.model_selection import cross_val_score

    cv_scores = cross_val_score(model, X_train, y_train, cv=10, scoring='accuracy')
    print(f"Cross-validation accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

    # 预测
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    # 混淆矩阵
    conf_matrix = confusion_matrix(y_test, y_pred)
    print("\nConfusion Matrix:")
    print(conf_matrix)

    # 分类报告
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

In [26]:
# F检验选择的特征
X_train, X_test, y_train, y_test = normalization_function(X_F, y_F)
get_model(X_train, X_test, y_train, y_test)

Cross-validation accuracy: 0.8336 ± 0.0238

Confusion Matrix:
[[204  29]
 [ 34 109]]

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.88      0.87       233
           1       0.79      0.76      0.78       143

    accuracy                           0.83       376
   macro avg       0.82      0.82      0.82       376
weighted avg       0.83      0.83      0.83       376



In [22]:
# mi
X_train, X_test, y_train, y_test = normalization_function(X_mi, y_mi)
get_model(X_train, X_test, y_train, y_test)

Cross-validation accuracy: 0.8137 ± 0.0257

Confusion Matrix:
[[203  30]
 [ 43 100]]

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.87      0.85       233
           1       0.77      0.70      0.73       143

    accuracy                           0.81       376
   macro avg       0.80      0.79      0.79       376
weighted avg       0.80      0.81      0.80       376



In [23]:
# RFE
X_train, X_test, y_train, y_test = normalization_function(X_RFE, y_RFE)
get_model(X_train, X_test, y_train, y_test)

Cross-validation accuracy: 0.8310 ± 0.0256

Confusion Matrix:
[[205  28]
 [ 38 105]]

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       233
           1       0.79      0.73      0.76       143

    accuracy                           0.82       376
   macro avg       0.82      0.81      0.81       376
weighted avg       0.82      0.82      0.82       376



In [24]:
# RF
X_train, X_test, y_train, y_test = normalization_function(X_RF, y_RF)
get_model(X_train, X_test, y_train, y_test)

Cross-validation accuracy: 0.8077 ± 0.0309

Confusion Matrix:
[[202  31]
 [ 44  99]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.87      0.84       233
           1       0.76      0.69      0.73       143

    accuracy                           0.80       376
   macro avg       0.79      0.78      0.78       376
weighted avg       0.80      0.80      0.80       376



In [25]:
# L1
X_train, X_test, y_train, y_test = normalization_function(X_l1, y_l1)
get_model(X_train, X_test, y_train, y_test)

Cross-validation accuracy: 0.8290 ± 0.0201

Confusion Matrix:
[[205  28]
 [ 33 110]]

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.88      0.87       233
           1       0.80      0.77      0.78       143

    accuracy                           0.84       376
   macro avg       0.83      0.82      0.83       376
weighted avg       0.84      0.84      0.84       376

